name: Call56AfkKick
version: 1.0-SNAPSHOT
main: com.kinoko2k.main.call56afkkick.Call56AfkKick
api-version: 1.17
authors: [ Kinoko_2K ]

commands:
  noafk:
    description: ยง3Confirm that you are not AFK.
    usage: /noafk
  afkreload:
    description: ยง3Reload Config
    usage: /afkreload
    permission: call56afk.reload
